### PR TITLE
Upgrade to 2.18.1 dart sdk

### PR DESCRIPTION
**Pull request by PandaGuerrier**
### All Submissions:

* [ ] Have you ensured there aren't other open [Pull Requests](../pulls) for the same update or change?
* [ ] Have you created a new branch for your changes and PR from that branch and not from your master branch?

### New Image Submissions:

1. [ ] Have you added your image to the [Github workflows](https://github.com/parkervcp/yolks/tree/master/.github/workflows)?
2. [ ] Have you updated the README list to contain your new image?

### CODE REVIEW

**Comment by parkervcp** [comment]
@PandaGuerrier This should probably be a separate dockerfile as this one is specifically for 2.17

**Comment by devnote-dev** [comment]
This isn't a case of just changing the version number, please see the contributing section of the README.

**Comment by PandaGuerrier** [comment]
Yes sorry, 

But can you create a 2.18 / 2.19 dart sdk for docker please ?

Thanks

**Comment by devnote-dev** [comment]
You generally make an issue in the [eggs repo](https://github.com/parkervcp/eggs) for egg changes, as that would need to be updated too.

**Comment by QuintenQVD0** [comment]
https://github.com/parkervcp/yolks/pull/135

**Comment by QuintenQVD0** [comment]
if merged, then I update the egg. install image will stay the same

**Pull request closed without merging**
