### PR TITLE
fix wine build error with debian buster

### PR DESCRIPTION
**Pull request by gOOvER**
### All Submissions:

* [x] Have you ensured there aren't other open [Pull Requests](../pulls) for the same update or change?
* [x] Have you created a new branch for your changes and PR from that branch and not from your master branch?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### Changelog for this PR:

- added missing depencies on Buster

### CODE REVIEW

**Comment by gOOvER** [comment]
pls wait with merge, until i update it to bullseye :)

**Comment by Software-Noob** [comment]
This shouldn't be necessary since base is now built for bullseye and the wine image is already successfully built?

**Comment by gOOvER** [comment]
> This shouldn't be necessary since base is now built for bullseye and the wine image is already successfully built?

this pr update to Bullseye. Now Buster repos are used in published image

**Comment by Software-Noob** [comment]
> > This shouldn't be necessary since base is now built for bullseye and the wine image is already successfully built?
> 
> this pr update to Bullseye. Now Buster repos are used in published image

Bullseye is used as far as I can see

https://github.com/parkervcp/yolks/blob/master/wine/latest/Dockerfile#L16

**Comment by gOOvER** [comment]
These 2 line should be in the Dockerfile

RUN     wget -O- -q https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/Debian_11/Release.key | apt-key add -
RUN     echo "deb http://download.opensuse.org/repositories/Emulators:/Wine:/Debian/Debian_11 ./" | tee /etc/apt/sources.list.d/wine-obs.list

They contain additinal packages for wine

**Pull request closed without merging**
