### PR TITLE
Add libnss3 to nodejs

### PR DESCRIPTION
**Pull request by Paultje52**
## Description
This PR adds `libnss3` as an dependency to the docker file for node 18, 19 and 20. This dependency is needed to run puppeteer.

### All Submissions:

* [x] Have you ensured there aren't other open [Pull Requests](../pulls) for the same update or change?
* [x] Have you created a new branch for your changes and PR from that branch and not from your master branch?

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
Wy not thr other nodejs images?

**Comment by Paultje52** [comment]
> Wy not the other nodejs images?

Because 16 will go EOL in less then a week and the versions before that are already EOL

**Comment by Paultje52** [comment]
> Honestly I already have a wings pr that fixes this issue that I am waiting on.

Great! Is it maybe possible to merge this PR and temporarily fix the issue? When your wings pr is merges, it can be removed. Maybe you can even remove more dependencies that are no longer needed 😄

**Comment by QuintenQVD0** [comment]
This has to wait. I need to append an extra fix. Npm 10 released and it only supports nofejs 16 or up

**Comment by QuintenQVD0** [comment]
> Honestly I already have a wings pr that fixes this issue that I am waiting on.

libnss3 is a network security layer. How does that related to any wings pr?

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Comment by gOOvER** [comment]
i would remove all deprecated nodejs version.

**Comment by QuintenQVD0** [comment]
> i would remove all deprecated nodejs version.

I get it 100% we keep them to keep the packages with the image up to date. as a lot of nodejs version are EOL and I do know that

**Comment by gOOvER** [comment]
Then I would remove it; because at least in the EU, the provider of outdated software can be held liable. There is no "compatibility"

And if an app needs under Node 18, the person can take that into his responsibility and make an image himself.

**Pull request merged**
