### PR TITLE
mono: replace lib32gcc-s1 with lib32gcc-s1-amd64-cross to support arm64

### PR DESCRIPTION
**Pull request by QuintenQVD0**
## Description

Replace lib32gcc-s1 with lib32gcc-s1-amd64-cross to support arm64 build.
afbeelding
afbeelding

### All Submissions:

* [x] Have you ensured there aren't other open [Pull Requests](../pulls) for the same update or change?
* [x] Have you created a new branch for your changes and PR from that branch and not from your master branch?

### CODE REVIEW

**Comment by gOOvER** [comment]
do this really work with arm64? i dont find anything about it

**Comment by QuintenQVD0** [comment]
> do this really work with arm64? i dont find anything about it.
> 
> If yes, we should replace it on every image

I have no idea, there debian repo description tells me yes, but it included difrend packages
afbeelding
afbeelding

**Comment by Software-Noob** [comment]
If you have no idea if your change works, then it should be tested thoroughly first. Please don't make changes on a whim. We must remember that many users and businesses can rely on these images and we can't suddenly break them all.

**Comment by QuintenQVD0** [comment]
I have no time in the close future to test this

**Pull request closed without merging**
