### PR TITLE
Added Bun Image

### PR DESCRIPTION
**Pull request by mratox**
## Description
Added Bun Image

### All Submissions:

* [X] Have you ensured there aren't other open [Pull Requests](../pulls) for the same update or change?
* [X] Have you created a new branch for your changes and PR from that branch and not from your master branch?

### New Image Submissions:

1. [X] Have you added your image to the [Github workflows](https://github.com/parkervcp/yolks/tree/master/.github/workflows)?
2. [X] Have you updated the README list to contain your new image?

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
Please use a coppy of our existing workflow files. Not something custom made.

**Comment by QuintenQVD0** [comment]
Also your way of making the docker file does not match ours. Like build for arm64

**Comment by mratox** [comment]
Take a look now, I'm ready to improve/change anything.

**Comment by QuintenQVD0** [comment]
> Take a look now, I'm ready to improve/change anything.

I already made the needed changes, please build the image locally (or where you have it rn) the exact way as it is here as the emptying the entrypoint.sh of them may not be needed

**Comment by mratox** [comment]
I have built and test both images (latest and canary) and they work without any problems.

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Comment by QuintenQVD0** [comment]
Now hope I did not mess up

**Pull request merged**
