### PR TITLE
feat: add altv game image

### PR DESCRIPTION
**Pull request by gOOvER**
### All Submissions:

* [x] Have you ensured there aren't other open [Pull Requests](../pulls) for the same update or change?
* [x] Have you created a new branch for your changes and PR from that branch and not from your master branch?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

### New Image Submissions:

1. [x] Have you added your image to the [Github workflows](https://github.com/parkervcp/yolks/tree/master/.github/workflows)?
2. [x] Have you updated the README list to contain your new image?

### CODE REVIEW

**Comment by gOOvER** [comment]
fix: https://github.com/parkervcp/eggs/issues/1543

**Review by Software-Noob — APPROVED** [review]
LGTM, thank you for contributing :+1:

**Comment by VibeGAMESNL** [comment]
@gOOvER Could you add support for .NET 7.0 to this image?

**Comment by gOOvER** [comment]
> @gOOvER Could you add support for .NET 7.0 to this image?

@VibeGAMESNL please test this image before; if it works, i'll push the changes

`ghcr.io/goover/games:altv`

**Comment by VibeGAMESNL** [comment]
> > @gOOvER Could you add support for .NET 7.0 to this image?
> 
> @VibeGAMESNL please test this image before; if it works, i'll push the changes
> 
> `ghcr.io/goover/games:altv`

@gOOvER Its working correctly

**Comment by gOOvER** [comment]
@VibeGAMESNL you can use the image from parker again. It's merged

**Pull request merged**
