### PR TITLE
Nodejs / add npm install npm@latest -g

### PR DESCRIPTION
**Pull request by gOOvER**
## Description

add npm install npm@latest -g to all images to prevent install errors like:

`Your cache folder contains root-owned files, due to a bug in npm previous versions of npm which has since been addressed.`

### All Submissions:

* [x] Have you ensured there aren't other open [Pull Requests](../pulls) for the same update or change?
* [x] Have you created a new branch for your changes and PR from that branch and not from your master branch?

### CODE REVIEW

**Review by parkervcp — COMMENTED** [review]
I'm mad that I need to even approve this...

**Review by parkervcp — APPROVED** [review]

**Comment by Software-Noob** [comment]
Why not just `npm cache clean --force` if the cache directory permissions are wrong? FYI The images now contain two layers of installing npm@latest.

**Comment by gOOvER** [comment]
> Why not just `npm cache clean --force` if the cache directory permissions are wrong? FYI The images now contain two layers of installing npm@latest.

because this was a bug in npm

**Comment by Software-Noob** [comment]
I don't see how this fixes anything. There's `npm -g install npm@latest` in the layer above this. Now there are two layers of installing npm? This is not a NPM version error. 

It's a misleading error whenever npm doesn't have permissions. Any error with `EACCES` or `EPERM` regarding cache dir will trigger it.  Error message itself is referring to 2018 for npm `8.12` where the referenced bug was actually implemented. The debug logs would show more, but it's most likely trying to make a hard link of the installed package for the cache.


<details>
<summary>example simulated error (not in pterodactyl)</summary>

```npm verb stack FetchError: Invalid response body while trying to fetch https://registry.npmjs.org/corepack: EACCES: permission denied, link '/data/data/com.testfolder/files/home/.npm/_cacache/tmp/9b99c620' -> '/data/data/com.testfolder/files/home/.npm/_cacache/content-v2/sha512/8b/29/d8d04509b38b390ebcba4956b8fb2955f88570f48241edffb01128b2dcdfb4580c453db04a422a8046fb9fdf7c7c9c31a25a64ac280c8f7892511b0798a7'```

</details>

**Comment by gOOvER** [comment]
> I don't see how this fixes anything. There's `npm -g install npm@latest` in the layer above this. Now there are two layers of installing npm? This is not a NPM version error.
> 
> It's a misleading error whenever npm doesn't have permissions. Any error with `EACCES` or `EPERM` regarding cache dir will trigger it. Error message itself is referring to 2018 for npm `8.12` where the referenced bug was actually implemented. The debug logs would show more, but it's most likely trying to make a hard link of the installed package for the cache.
> 
> example simulated error (not in pterodactyl)

i think, i will be out here; you are doing nothing for months in here. Its a simple npm update which is needed

**Comment by Software-Noob** [comment]
Discussion is healthy. You taking issues personally is not.

All this did was move the npm install to a new layer and increase the image size. The result is the same even if you move layers.

**Pull request merged**
