### PR TITLE
Added Elixir images

### PR DESCRIPTION
**Pull request by avoxmr**
## Description
Added Elixir Egg.

### All Submissions:

* [X] Have you ensured there aren't other open [Pull Requests](../pulls) for the same update or change?
* [X] Have you created a new branch for your changes and PR from that branch and not from your master branch?

### New Image Submissions:

1. [X] Have you added your image to the [Github workflows](https://github.com/parkervcp/yolks/tree/master/.github/workflows)?
2. [X] Have you updated the README list to contain your new image?

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
You are missing the ENV in every docker file before the HOME variable

**Comment by avoxmr** [comment]
Hi, what do you mean?
Is there anything wrong in:
ENV USER=container HOME=/home/container

**Comment by QuintenQVD0** [comment]
> Hi, what do you mean? Is there anything wrong in: ENV USER=container HOME=/home/container

Sorry.  It looks like my phone is messing up the format

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Pull request merged**
