### PR TITLE
add libsdl2-2.0-0 to prevent errors

### PR DESCRIPTION
**Pull request by gOOvER**
## Description

add libsdl2-2.0-0 to prevent errors

### All Submissions:

* [x] Have you ensured there aren't other open [Pull Requests](../pulls) for the same update or change?
* [x] Have you created a new branch for your changes and PR from that branch and not from your master branch?

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
Wy is this a 2nd PR can this not just be added to #118

**Comment by gOOvER** [comment]
> Wy is this a 2nd PR can this not just be added to #118

because its a direct edit

**Comment by QuintenQVD0** [comment]
there both wine?

**Comment by gOOvER** [comment]
> there both wine?

wine stable and staging

**Review by QuintenQVD0 — APPROVED** [review]

**Pull request merged**
