### PR TITLE
Add zip/unzip to 

### PR DESCRIPTION
**Pull request by Stigstille**
## Description

This adds the `zip` and `unzip` packages. As simple as that

### All Submissions:

* [x] Have you ensured there aren't other open [Pull Requests](../pulls) for the same update or change?
* [x] Have you created a new branch for your changes and PR from that branch and not from your master branch

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
@Stigstille You missed like 9 or 10 diffrend docker files

**Comment by Stigstille** [comment]
oh! mb... let me add it to all of them (i thought I was only supposed to change the one I was going to use)

**Comment by Stigstille** [comment]
should be good now if I didnt mess anything up

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Pull request merged**
