### PR TITLE
TeaSpeak replaced youtube-dl with ytdlp

### PR DESCRIPTION
**Pull request by V01D-PH03N1X**
## Description

I have replaced youtube-dl with ytdlp because youtube-dl can no longer be developed further. Because it was taken down.
youtube-dl takedown report: 
https://yt-dl.org/
https://openjur.de/u/2466945.html

### All Submissions:

* [X] Have you ensured there aren't other open [Pull Requests](../pulls) for the same update or change?
* [X] Have you created a new branch for your changes and PR from that branch and not from your master branch?

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
but it is still saved as the youtube-dl binary name?

**Comment by gOOvER** [comment]
TeaSpeak is dead since over 2 years and should not longer used

**Comment by V01D-PH03N1X** [comment]
> but it is still saved as the youtube-dl binary name?

Yes, it has the same syntax as youtube-dl. It is a fork of youtube-dl and is active maintained. 



> TeaSpeak is dead since over 2 years and should not longer used

Better than Discord or TeamSpeak...
Some People are using it.

**Review by QuintenQVD0 — APPROVED** [review]
Even that TeaSpeak is not actively been maintained, this fix is needed to keep it at least running

**Pull request merged**
