### PR TITLE
add Steam Proton Image

### PR DESCRIPTION
**Pull request by gOOvER**
## Description

This image adds support for Steam Proton.

- This image uses Proton GE [https://github.com/GloriousEggroll/proton-ge-custom](https://github.com/GloriousEggroll/proton-ge-custom)
- ${SRCDS_APPID} is needed as Variable
- STEAM_COMPAT_CLIENT_INSTALL_PATH & STEAM_COMPAT_DATA_PATH is set in entrypoint and must not be set as variable

usage startupcmd:
`proton run <startup>`

maybe packages are missing

### All Submissions:

* [x] Have you ensured there aren't other open [Pull Requests](../pulls) for the same update or change?
* [x] Have you created a new branch for your changes and PR from that branch and not from your master branch?

### New Image Submissions:

1. [x] Have you added your image to the [Github workflows](https://github.com/parkervcp/yolks/tree/master/.github/workflows)?
2. [x] Have you updated the README list to contain your new image?

### CODE REVIEW

**Comment by Software-Noob** [comment]
If `SRCDS_APPID `is a required variable for this to function, it should exit with a warning when it's not set for easier troubleshooting

**Comment by gOOvER** [comment]
oh yes, you are right. i will add this later

**Comment by gOOvER** [comment]
> If `SRCDS_APPID `is a required variable for this to function, it should exit with a warning when it's not set for easier troubleshooting

added

**Comment by QuintenQVD0** [comment]
I tried using winetricks, it does not work.

No wineserver found

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Pull request merged**
