### PR TITLE
feat: add mohaa game image

### PR DESCRIPTION
**Pull request by Th3Dilli**
This PR adds a new image to be used for the Medal of Honor: Allied Assault egg

i thought ill create a new image since it depends on an 32 bit library that is most likely not be useful for any other game

### CODE REVIEW

**Comment by gOOvER** [comment]
Why is this needed? I see not really, that something changed

**Comment by Th3Dilli** [comment]
i had to add `lib32stdc++6 libstdc++5:i386`  to get the server to run

**Comment by gOOvER** [comment]
i think you can add the libs to base image and there is no need for an own image

**Comment by Th3Dilli** [comment]
i added the libs to the base image and also changed the egg to the base image 
https://github.com/parkervcp/eggs/pull/1352

**Review by parkervcp — APPROVED** [review]

**Comment by Software-Noob** [comment]
@Th3Dilli The base image is multiarch and `lib32stdc++6 ` doesn't exist on ARM64. Please create a new PR with a separate image to add it.

Remember to add `dpkg --add-architecture i386` since it's missing from this one, which is why also building it failed on installing the 32-bit package `libstdc++5:i386`

**Pull request merged**
