### PR TITLE
update all  wine images to use latest keyrings and added wine devel

### PR DESCRIPTION
**Pull request by gOOvER**
## Description

- update all keyrings to use new 
- added wine devel
- added missing user creation
- cleanup

### All Submissions:

* [x] Have you ensured there aren't other open [Pull Requests](../pulls) for the same update or change?
* [x] Have you created a new branch for your changes and PR from that branch and not from your master branch?

### New Image Submissions:

1. [x] Have you added your image to the [Github workflows](https://github.com/parkervcp/yolks/tree/master/.github/workflows)?
2. [x] Have you updated the README list to contain your new image?

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
@gOOvER making the user will fail as the base image already has this user so there is no need to make the container user.

**Comment by gOOvER** [comment]
> @gOOvER making the user will fail as the base image already has this user so there is no need to make the container user.

my fail, becaue i use official base images

**Review by QuintenQVD0 — APPROVED** [review]
LGTM! @parkervcp it is up to you if we want wine devel

**Comment by gOOvER** [comment]
devel ist the same as staging. Staging have more Wine specific Patches from Proton Project

**Pull request merged**
