### PR TITLE
[Arma 3] Fix SteamCMD Crashing

### PR DESCRIPTION
**Pull request by lilkingjr1**
## Description

Partially resolves parkervcp/eggs#1965 by addressing said issue present in the Arma 3 yolk. Exact reasoning for the crash is still unknown, but I have found that switching to Ubuntu as the base image somewhat resolves the issue. It's not ideal to switch to Ubuntu, so this fix is a temporary stop-gap to at least get things working again until a more proper solution can be found for Debian. Details of the changes made to make this work can be found in the commit notes.

The image is currently live for testing purposes here if you would like:
`ghcr.io/lilkingjr1/arma3-yolk:main`

### All Submissions:

* [x] Have you ensured there aren't other open [Pull Requests](../pulls) for the same update or change?
* [x] Have you created a new branch for your changes and PR from that branch and not from your master branch?

### CODE REVIEW

**Comment by lilkingjr1** [comment]
Put this PR on hold; [a new development](https://github.com/parkervcp/eggs/issues/1965#issuecomment-1328152220) has been made that may allow us to keep Debian as the base image.

**Comment by gOOvER** [comment]
Building failed 

```
 > [4/9] RUN         mv /usr/lib/libnss_wrapper.so /usr/lib/libnss_wrapper_32.so             && apt-get install -y libnss-wrapper:
#0 0.051 mv: cannot stat '/usr/lib/libnss_wrapper.so': No such file or directory
------
Dockerfile:41
--------------------
  40 |     ## Prepare NSS Wrapper for the entrypoint as a workaround for Arma 3 requiring a valid UID
  41 | >>> RUN         mv /usr/lib/libnss_wrapper.so /usr/lib/libnss_wrapper_32.so \
  42 | >>>             && apt-get install -y libnss-wrapper
  43 |     ENV         NSS_WRAPPER_PASSWD=/tmp/passwd NSS_WRAPPER_GROUP=/tmp/group
--------------------
ERROR: failed to solve: process "/bin/sh -c mv /usr/lib/libnss_wrapper.so /usr/lib/libnss_wrapper_32.so             && apt-get install -y libnss-wrapper" did not complete successfully: exit code: 1
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c mv /usr/lib/libnss_wrapper.so /usr/lib/libnss_wrapper_32.so             && apt-get install -y libnss-wrapper" did not complete successfully: exit code: 1
```

**Comment by lilkingjr1** [comment]
@gOOvER If you're using this (https://github.com/gOOvER/own-pterodactyl-images/tree/main/games/arma3ubuntu) as your testing image, it does not match this PR. Your Dockerfile uses Debian as the base image.

**Comment by lilkingjr1** [comment]
Superseded by #100.

**Pull request closed without merging**
