### PR TITLE
add xvfb, becasue some steamgames need it outside wine

### PR DESCRIPTION
**Pull request by gOOvER**
## Description

add xvfb, becasue some steamgames need it outside wine
### All Submissions:

* [x] Have you ensured there aren't other open [Pull Requests](../pulls) for the same update or change?
* [x] Have you created a new branch for your changes and PR from that branch and not from your master branch?

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
what is the reason you did not add the default xvfb variables? and you did not apply it to the ubuntu image?

**Comment by gOOvER** [comment]
> what is the reason you did not add the default xvfb variables? and you did not apply it to the ubuntu image?

There is no Variable needed. Take a look into Wine Image, why variably is used

**Comment by gOOvER** [comment]
ill commit all in 1

**Comment by QuintenQVD0** [comment]
fine for me

**Pull request closed without merging**
