### PR TITLE
Add version 20

### PR DESCRIPTION
**Pull request by Loki-101**
## Description

Added node version 20; tested and built successfully with buildx

### All Submissions:

* [ X] Have you ensured there aren't other open [Pull Requests](../pulls) for the same update or change?
* [ X] Have you created a new branch for your changes and PR from that branch and not from your master branch?

### CODE REVIEW

**Comment by Loki-101** [comment]
I have never messed with Github images or actions before. I'm not sure if it's all automatic or if I was supposed to do something to make sure the image gets built with the others. Because I'm not sure about this, I haven't made a pull request to edit the README in the base to include this image in the list yet.

**Comment by danny6167** [comment]
You want to add 20 to this file to make it build
https://github.com/parkervcp/yolks/blob/master/.github/workflows/nodejs.yml

**Comment by QuintenQVD0** [comment]
20 is not an lts release. 21 will

**Comment by QuintenQVD0** [comment]
Where would you even need 20?

**Comment by Loki-101** [comment]
Idk, someone requested it in the Discord and I just figured why not.

**Review by QuintenQVD0 — APPROVED** [review]
LGTM!

**Pull request merged**
