### PR TITLE
Added version 15 (postgres)

### PR DESCRIPTION
**Pull request by mratox**
## Description
Added version 15 (postgres)

### All Submissions:

* [X] Have you ensured there aren't other open [Pull Requests](../pulls) for the same update or change?
* [X] Have you created a new branch for your changes and PR from that branch and not from your master branch?

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
Wy close?

**Comment by mratox** [comment]
I was about to make a new pterodactyl egg, but i decided to make a pypy egg instand.

**Comment by mratox** [comment]
If someone decided to do it, you may merge this.

**Comment by mratox** [comment]
Or maybe i will do it tomorrow.

**Comment by dagbs** [comment]
why was this not merged?

**Pull request closed without merging**
