### PR TITLE
Cleanup java images

### PR DESCRIPTION
**Pull request by gOOvER**
## Description

- image cleanup
- update images to jammy

### All Submissions:

* [x] Have you ensured there aren't other open [Pull Requests](../pulls) for the same update or change?
* [x] Have you created a new branch for your changes and PR from that branch and not from your master branch?

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
I see, this is comming because they have an entrypoint now in there images, see:


https://github.com/adoptium/containers/pull/392
https://github.com/adoptium/containers/commit/05b7f082746228466ceacf43dd0c21e9a0ba2b84#diff-f039b99538d3a63ca08a6fd9e5a9ff5f5a6108066c058902dacbea9b928e635f

**Comment by gOOvER** [comment]
> @gOOvER Edit: the cleanup is fine and the move to jammy.
> 
> I now see the issue that they introduced. does it work when you set it to bash and not sh and even more to the full path so /bin/bash instead of just sh or bash.
> 
> edit 2:
> Tomcat just set the entrypoint to https://github.com/docker-library/tomcat/pull/303/commits/55546d611e41cde189ba9e820c25cb5bf18a33f9

dont Test IT, but this works fine for me

**Comment by parkervcp** [comment]
I'll pr a fix for the script perms instead of updating all this. That would fix this.

**Comment by parkervcp** [comment]
My PR #176 resolves this without editing all the Dockerfiles.

**Pull request merged**
